// FEATURE (27/08/2026, pedido del cliente): ciudades/localidades
// agrupadas por provincia, para que el <select> de Ciudad (Register.jsx y
// ConfiguracionPrivacidad.jsx) dependa de qué Provincia esté elegida --
// antes Ciudad era un campo de texto libre sin relación con Provincia.
//
// Las claves son exactamente los mismos "value" que utils/provincias.js
// (si se agrega/renombra una provincia ahí, hay que actualizar esto
// también). No es la lista completa y oficial de localidades de INDEC
// (son miles) -- es una selección de las ciudades/localidades más
// conocidas de cada provincia, suficiente para un formulario de compra.
// Caso especial: "Ciudad Autónoma de Buenos Aires" no tiene "ciudades"
// propias (es una sola), así que ahí se listan sus 48 barrios oficiales
// en su lugar.
//
// Si el usuario no encuentra su localidad en la lista, el <select> tiene
// una opción "Otra (especificar)" al final que revela un campo de texto
// libre -- ver Register.jsx/ConfiguracionPrivacidad.jsx.
export const CIUDADES_POR_PROVINCIA = {
  "Buenos Aires": [
    "Adrogué",
    "Avellaneda",
    "Azul",
    "Bahía Blanca",
    "Balcarce",
    "Baradero",
    "Berazategui",
    "Berisso",
    "Bolívar",
    "Bragado",
    "Campana",
    "Cañuelas",
    "Carmen de Patagones",
    "Caseros",
    "Chacabuco",
    "Chascomús",
    "Chivilcoy",
    "Coronel Suárez",
    "Dolores",
    "Ensenada",
    "Escobar",
    "Esteban Echeverría",
    "Ezeiza",
    "Florencio Varela",
    "General Rodríguez",
    "General Villegas",
    "Guernica",
    "Haedo",
    "Hurlingham",
    "Ituzaingó",
    "José C. Paz",
    "Junín",
    "La Matanza",
    "La Plata",
    "Lanús",
    "Las Flores",
    "Lincoln",
    "Lobos",
    "Lomas de Zamora",
    "Luján",
    "Malvinas Argentinas",
    "Mar del Plata",
    "Marcos Paz",
    "Mercedes",
    "Merlo",
    "Miramar",
    "Monte Grande",
    "Moreno",
    "Morón",
    "Necochea",
    "Olavarría",
    "Pehuajó",
    "Pergamino",
    "Pilar",
    "Pinamar",
    "Presidente Perón",
    "Quilmes",
    "Ramos Mejía",
    "Rauch",
    "Saladillo",
    "San Antonio de Areco",
    "San Fernando",
    "San Isidro",
    "San Justo",
    "San Martín",
    "San Miguel",
    "San Nicolás de los Arroyos",
    "San Pedro",
    "San Vicente",
    "Tandil",
    "Tapalqué",
    "Tigre",
    "Tornquist",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Vicente López",
    "Villa Gesell",
    "Zárate"
  ],
  "Catamarca": [
    "Andalgalá",
    "Antofagasta de la Sierra",
    "Belén",
    "Chumbicha",
    "El Rodeo",
    "Fiambalá",
    "Huillapima",
    "Pomán",
    "Recreo",
    "San Fernando del Valle de Catamarca",
    "Santa María",
    "Tinogasta",
    "Valle Viejo"
  ],
  "Chaco": [
    "Barranqueras",
    "Charata",
    "Colonia Elisa",
    "Corzuela",
    "Fontana",
    "General José de San Martín",
    "General Pinedo",
    "Juan José Castelli",
    "La Leonesa",
    "Las Breñas",
    "Las Palmas",
    "Machagai",
    "Margarita Belén",
    "Pampa del Infierno",
    "Presidencia de la Plaza",
    "Presidencia Roque Sáenz Peña",
    "Puerto Tirol",
    "Quitilipi",
    "Resistencia",
    "Tres Isletas",
    "Villa Ángela",
    "Villa Berthet"
  ],
  "Chubut": [
    "Camarones",
    "Cholila",
    "Comodoro Rivadavia",
    "Corcovado",
    "Dolavon",
    "El Hoyo",
    "El Maitén",
    "Epuyén",
    "Esquel",
    "Gaiman",
    "Gastre",
    "Gobernador Costa",
    "Gualjaina",
    "José de San Martín",
    "Lago Puelo",
    "Paso de Indios",
    "Puerto Madryn",
    "Puerto Pirámides",
    "Rada Tilly",
    "Rawson",
    "Río Mayo",
    "Sarmiento",
    "Tecka",
    "Telsen",
    "Trelew",
    "Trevelin"
  ],
  "Ciudad Autónoma de Buenos Aires": [
    "Agronomía",
    "Almagro",
    "Balvanera",
    "Barracas",
    "Belgrano",
    "Boedo",
    "Caballito",
    "Chacarita",
    "Coghlan",
    "Colegiales",
    "Constitución",
    "Flores",
    "Floresta",
    "La Boca",
    "La Paternal",
    "Liniers",
    "Mataderos",
    "Monserrat",
    "Monte Castro",
    "Nueva Pompeya",
    "Núñez",
    "Palermo",
    "Parque Avellaneda",
    "Parque Chacabuco",
    "Parque Chas",
    "Parque Patricios",
    "Puerto Madero",
    "Recoleta",
    "Retiro",
    "Saavedra",
    "San Cristóbal",
    "San Nicolás",
    "San Telmo",
    "Vélez Sársfield",
    "Versalles",
    "Villa Crespo",
    "Villa del Parque",
    "Villa Devoto",
    "Villa General Mitre",
    "Villa Lugano",
    "Villa Luro",
    "Villa Ortúzar",
    "Villa Pueyrredón",
    "Villa Real",
    "Villa Riachuelo",
    "Villa Santa Rita",
    "Villa Soldati",
    "Villa Urquiza"
  ],
  "Córdoba": [
    "Alta Gracia",
    "Arroyito",
    "Bell Ville",
    "Colonia Caroya",
    "Córdoba",
    "Corral de Bustos",
    "Cosquín",
    "Cruz del Eje",
    "Despeñaderos",
    "General Cabrera",
    "Hernando",
    "Jesús María",
    "La Calera",
    "La Falda",
    "Laboulaye",
    "Leones",
    "Malagueño",
    "Marcos Juárez",
    "Mina Clavero",
    "Morteros",
    "Nono",
    "Oncativo",
    "Río Ceballos",
    "Río Cuarto",
    "Río Segundo",
    "Río Tercero",
    "Salsipuedes",
    "San Francisco",
    "Ucacha",
    "Unquillo",
    "Villa Allende",
    "Villa Carlos Paz",
    "Villa de Soto",
    "Villa del Totoral",
    "Villa Dolores",
    "Villa General Belgrano",
    "Villa María"
  ],
  "Corrientes": [
    "Bella Vista",
    "Corrientes",
    "Curuzú Cuatiá",
    "Empedrado",
    "Esquina",
    "Gobernador Virasoro",
    "Goya",
    "Itatí",
    "Ituzaingó",
    "La Cruz",
    "Mburucuyá",
    "Mercedes",
    "Monte Caseros",
    "Paso de los Libres",
    "Saladas",
    "San Cosme",
    "San Luis del Palmar",
    "Santa Lucía",
    "Santo Tomé",
    "Sauce",
    "Yapeyú"
  ],
  "Entre Ríos": [
    "Basavilbaso",
    "Chajarí",
    "Colón",
    "Concepción del Uruguay",
    "Concordia",
    "Crespo",
    "Diamante",
    "Federación",
    "Federal",
    "General Ramírez",
    "Gualeguay",
    "Gualeguaychú",
    "Hernandarias",
    "La Paz",
    "Libertador San Martín",
    "Nogoyá",
    "Paraná",
    "Rosario del Tala",
    "San José",
    "San Salvador",
    "Santa Elena",
    "Ubajay",
    "Viale",
    "Victoria",
    "Villa Elisa",
    "Villa Paranacito",
    "Villaguay"
  ],
  "Formosa": [
    "Clorinda",
    "Comandante Fontana",
    "El Colorado",
    "Estanislao del Campo",
    "Formosa",
    "Herradura",
    "Ibarreta",
    "Ingeniero Juárez",
    "Laguna Blanca",
    "Laguna Yema",
    "Las Lomitas",
    "Palo Santo",
    "Pirané",
    "Pozo del Tigre",
    "Riacho He-Hé",
    "Villa General Güemes"
  ],
  "Jujuy": [
    "Abra Pampa",
    "Caimancito",
    "Calilegua",
    "El Carmen",
    "Fraile Pintado",
    "Humahuaca",
    "La Quiaca",
    "Libertador General San Martín",
    "Maimará",
    "Monterrico",
    "Palpalá",
    "Perico",
    "Purmamarca",
    "San Pedro de Jujuy",
    "San Salvador de Jujuy",
    "Santa Catalina",
    "Susques",
    "Tilcara",
    "Valle Grande",
    "Volcán",
    "Yavi"
  ],
  "La Pampa": [
    "Alpachiri",
    "Alta Italia",
    "Anguil",
    "Bernasconi",
    "Casa de Piedra",
    "Catriló",
    "Colonia 25 de Mayo",
    "Doblas",
    "Eduardo Castex",
    "General Acha",
    "General Pico",
    "General San Martín",
    "Guatraché",
    "Ingeniero Luiggi",
    "Intendente Alvear",
    "Jacinto Aráuz",
    "La Adela",
    "Macachín",
    "Miguel Riglos",
    "Parera",
    "Puelén",
    "Quemú Quemú",
    "Rancul",
    "Realicó",
    "Santa Isabel",
    "Santa Rosa",
    "Toay",
    "Trenel",
    "Uriburu",
    "Victorica",
    "Winifreda"
  ],
  "La Rioja": [
    "Aimogasta",
    "Anillaco",
    "Chamical",
    "Chepes",
    "Chilecito",
    "Famatina",
    "Guandacol",
    "La Rioja",
    "Malanzán",
    "Nonogasta",
    "Olta",
    "Patquía",
    "San Blas de los Sauces",
    "Sañogasta",
    "Ulapes",
    "Villa Castelli",
    "Villa Sanagasta",
    "Villa Unión",
    "Vinchina"
  ],
  "Mendoza": [
    "Chacras de Coria",
    "General Alvear",
    "Godoy Cruz",
    "Guaymallén",
    "Junín",
    "La Paz",
    "Las Heras",
    "Luján de Cuyo",
    "Maipú",
    "Malargüe",
    "Mendoza",
    "Potrerillos",
    "Rivadavia",
    "San Carlos",
    "San Martín",
    "San Rafael",
    "Tunuyán",
    "Tupungato",
    "Uspallata",
    "Vista Flores"
  ],
  "Misiones": [
    "25 de Mayo",
    "Apóstoles",
    "Aristóbulo del Valle",
    "Bernardo de Irigoyen",
    "Campo Grande",
    "Campo Viera",
    "Candelaria",
    "Cerro Azul",
    "Comandante Andresito",
    "Concepción de la Sierra",
    "Corpus",
    "El Soberbio",
    "Eldorado",
    "Garupá",
    "Jardín América",
    "Leandro N. Alem",
    "Montecarlo",
    "Oberá",
    "Panambí",
    "Posadas",
    "Puerto Esperanza",
    "Puerto Iguazú",
    "Puerto Rico",
    "Ruiz de Montoya",
    "San Ignacio",
    "San Javier",
    "San Pedro",
    "San Vicente",
    "Santa Ana",
    "Wanda"
  ],
  "Neuquén": [
    "Aluminé",
    "Andacollo",
    "Añelo",
    "Buta Ranquil",
    "Centenario",
    "Chos Malal",
    "Cutral Có",
    "Junín de los Andes",
    "Las Lajas",
    "Loncopué",
    "Neuquén",
    "Piedra del Águila",
    "Plaza Huincul",
    "Plottier",
    "Rincón de los Sauces",
    "San Martín de los Andes",
    "San Patricio del Chañar",
    "Villa La Angostura",
    "Villa Pehuenia",
    "Zapala"
  ],
  "Río Negro": [
    "Allen",
    "Catriel",
    "Chimpay",
    "Choele Choel",
    "Cinco Saltos",
    "Cipolletti",
    "El Bolsón",
    "General Conesa",
    "General Roca",
    "Ingeniero Jacobacci",
    "Lamarque",
    "Las Grutas",
    "Luis Beltrán",
    "Maquinchao",
    "Ñorquincó",
    "Pilcaniyeu",
    "Río Colorado",
    "San Antonio Oeste",
    "San Carlos de Bariloche",
    "Sierra Colorada",
    "Valcheta",
    "Viedma"
  ],
  "Salta": [
    "Aguaray",
    "Angastaco",
    "Animaná",
    "Apolinario Saravia",
    "Cachi",
    "Cafayate",
    "Campo Quijano",
    "Cerrillos",
    "Chicoana",
    "Coronel Moldes",
    "El Carril",
    "El Galpón",
    "Embarcación",
    "General Güemes",
    "General Mosconi",
    "Guachipas",
    "Hipólito Yrigoyen",
    "Iruya",
    "Joaquín V. González",
    "La Caldera",
    "La Candelaria",
    "La Merced",
    "La Poma",
    "La Viña",
    "Las Lajitas",
    "Los Toldos",
    "Metán",
    "Molinos",
    "Nazareno",
    "Payogasta",
    "Rosario de la Frontera",
    "Rosario de Lerma",
    "Salta",
    "Salvador Mazza",
    "San Antonio de los Cobres",
    "San Carlos",
    "San Lorenzo",
    "San Ramón de la Nueva Orán",
    "Santa Victoria Este",
    "Tartagal"
  ],
  "San Juan": [
    "25 de Mayo",
    "Albardón",
    "Angaco",
    "Barreal",
    "Calingasta",
    "Caucete",
    "Chimbas",
    "Iglesia",
    "Nueve de Julio",
    "Pocito",
    "Rawson",
    "Rivadavia",
    "San Agustín del Valle Fértil",
    "San José de Jáchal",
    "San Juan",
    "San Martín",
    "Santa Lucía",
    "Sarmiento",
    "Ullum",
    "Villa Krause",
    "Zonda"
  ],
  "San Luis": [
    "Buena Esperanza",
    "Candelaria",
    "Concarán",
    "Justo Daract",
    "La Punta",
    "La Toma",
    "Luján",
    "Naschel",
    "Quines",
    "Renca",
    "San Francisco del Monte de Oro",
    "San Luis",
    "Santa Rosa de Conlara",
    "Tilisarao",
    "Unión",
    "Villa de Merlo",
    "Villa General Roca",
    "Villa Mercedes"
  ],
  "Santa Cruz": [
    "28 de Noviembre",
    "Caleta Olivia",
    "Comandante Luis Piedrabuena",
    "El Calafate",
    "El Chaltén",
    "Gobernador Gregores",
    "Jaramillo",
    "Las Heras",
    "Los Antiguos",
    "Perito Moreno",
    "Pico Truncado",
    "Puerto Deseado",
    "Puerto San Julián",
    "Puerto Santa Cruz",
    "Río Gallegos",
    "Río Turbio",
    "Tres Lagos"
  ],
  "Santa Fe": [
    "Arroyo Seco",
    "Avellaneda",
    "Cañada de Gómez",
    "Capitán Bermúdez",
    "Casilda",
    "Coronda",
    "Esperanza",
    "Firmat",
    "Gálvez",
    "Granadero Baigorria",
    "Rafaela",
    "Reconquista",
    "Rosario",
    "Rufino",
    "San Javier",
    "San Justo",
    "San Lorenzo",
    "Santa Fe",
    "Santo Tomé",
    "Sunchales",
    "Tostado",
    "Venado Tuerto",
    "Vera",
    "Villa Constitución",
    "Villa Gobernador Gálvez",
    "Villa Ocampo"
  ],
  "Santiago del Estero": [
    "Añatuya",
    "Bandera",
    "Clodomira",
    "Colonia Dora",
    "Fernández",
    "Frías",
    "La Banda",
    "Loreto",
    "Monte Quemado",
    "Ojo de Agua",
    "Quimilí",
    "Santiago del Estero",
    "Selva",
    "Suncho Corral",
    "Termas de Río Hondo"
  ],
  "Tierra del Fuego, Antártida e Islas del Atlántico Sur": [
    "Puerto Almanza",
    "Río Grande",
    "San Sebastián",
    "Tolhuin",
    "Ushuaia"
  ],
  "Tucumán": [
    "Aguilares",
    "Alderetes",
    "Amaicha del Valle",
    "Banda del Río Salí",
    "Bella Vista",
    "Burruyacú",
    "Colalao del Valle",
    "Concepción",
    "El Manantial",
    "Famaillá",
    "Graneros",
    "Juan Bautista Alberdi",
    "La Cocha",
    "Las Talitas",
    "Leales",
    "Lules",
    "Monteros",
    "Río Chico",
    "San Miguel de Tucumán",
    "San Pedro de Colalao",
    "Simoca",
    "Tafí del Valle",
    "Tafí Viejo",
    "Trancas",
    "Yerba Buena"
  ]
};
