"""agrega campos de pago de mercado pago a pedidos

Revision ID: 3b6bbd6be94c
Revises: 102a93be4c44
Create Date: 2026-08-18 09:56:10.299123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6bbd6be94c'
down_revision: Union[str, Sequence[str], None] = '102a93be4c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('mp_preference_id', sa.String(length=64), nullable=True))
    op.add_column('pedidos', sa.Column('mp_payment_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_pedidos_mp_payment_id'), 'pedidos', ['mp_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_mp_payment_id'), table_name='pedidos')
    op.drop_column('pedidos', 'mp_payment_id')
    op.drop_column('pedidos', 'mp_preference_id')
    # ### end Alembic commands ###
